OBJS = source/01_hello_SDL.cpp
CC = g++
COMPILER_FLAGS = `sdl2-config --cflags`
LINKER_FLAGS = -lSDL2
OBJ_NAME = 01_hello_SDL
all : $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)
clean : 
	rm -rf $(OBJ_NAME)
